[profile.default]
solc = '0.8.20'
out = 'out'
fuzz_runs = 1000
optimizer_runs = 10_000
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
  "prb-test/=lib/prb-test/src/",
  "@layerzero/=lib/@layerzero/contracts/lzApp/",
  "forge-std/=lib/forge-std/src/",
  "@types/=src/types/",
  "@interfaces/=src/interfaces/",
]

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000

[profile.test]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
src = 'src/test'

[rpc_endpoints]
base-goerli = "${BASE_GOERLI_RPC}"
goerli = "${ETH_GOERLI_RPC}"
arb-goerli = "${ARB_GOERLI_RPC}"
op-goerli = "${OP_GOERLI_RPC}"
bsc-goerli = "${BSC_GOERLI_RPC}"
avax-goerli = "${AVAX_GOERLI_RPC}"
poly-goerli = "${POLY_GOERLI_RPC}"
moon-goerli = "${MOON_GOERLI_RPC}"

[fmt]
line_length = 90
tab_width = 4
bracket_spacing = false
int_types = 'long'
quote_style = 'double'
number_underscore = 'thousands'
multiline_func_header = 'all'
